from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 283)
        MainWindow.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainmenu = QtWidgets.QWidget()
        self.mainmenu.setEnabled(True)
        self.mainmenu.setObjectName("mainmenu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainmenu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settings_button = QtWidgets.QPushButton(self.mainmenu)
        self.settings_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.settings_button.setFont(font)
        self.settings_button.setObjectName("settings_button")
        self.gridLayout_2.addWidget(self.settings_button, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.connect_button = QtWidgets.QPushButton(self.mainmenu)
        self.connect_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.connect_button.setFont(font)
        self.connect_button.setObjectName("connect_button")
        self.gridLayout_2.addWidget(self.connect_button, 1, 1, 1, 1)
        self.close_button = QtWidgets.QPushButton(self.mainmenu)
        self.close_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.close_button.setFont(font)
        self.close_button.setObjectName("close_button")
        self.gridLayout_2.addWidget(self.close_button, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 2, 1, 1)
        self.connect_button.raise_()
        self.close_button.raise_()
        self.settings_button.raise_()
        self.stackedWidget.addWidget(self.mainmenu)
        self.sql_logging = QtWidgets.QWidget()
        self.sql_logging.setObjectName("sql_logging")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.sql_logging)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_sql_input_username = QtWidgets.QLineEdit(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_sql_input_username.setFont(font)
        self.lineEdit_sql_input_username.setObjectName("lineEdit_sql_input_username")
        self.gridLayout_5.addWidget(self.lineEdit_sql_input_username, 2, 1, 1, 1)
        self.pushButton_sql_login_login = QtWidgets.QPushButton(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_sql_login_login.setFont(font)
        self.pushButton_sql_login_login.setObjectName("pushButton_sql_login_login")
        self.gridLayout_5.addWidget(self.pushButton_sql_login_login, 4, 0, 1, 1)
        self.label_sql_login_passwd = QtWidgets.QLabel(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_sql_login_passwd.setFont(font)
        self.label_sql_login_passwd.setObjectName("label_sql_login_passwd")
        self.gridLayout_5.addWidget(self.label_sql_login_passwd, 3, 0, 1, 1)
        self.lineEdit_sql_input_ip = QtWidgets.QLineEdit(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_sql_input_ip.setFont(font)
        self.lineEdit_sql_input_ip.setObjectName("lineEdit_sql_input_ip")
        self.gridLayout_5.addWidget(self.lineEdit_sql_input_ip, 1, 1, 1, 1)
        self.pushButton_sql_login_close = QtWidgets.QPushButton(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_sql_login_close.setFont(font)
        self.pushButton_sql_login_close.setObjectName("pushButton_sql_login_close")
        self.gridLayout_5.addWidget(self.pushButton_sql_login_close, 4, 1, 1, 1)
        self.label_sql_login_username = QtWidgets.QLabel(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_sql_login_username.setFont(font)
        self.label_sql_login_username.setObjectName("label_sql_login_username")
        self.gridLayout_5.addWidget(self.label_sql_login_username, 2, 0, 1, 1)
        self.label_sql_login_ip = QtWidgets.QLabel(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_sql_login_ip.setFont(font)
        self.label_sql_login_ip.setObjectName("label_sql_login_ip")
        self.gridLayout_5.addWidget(self.label_sql_login_ip, 1, 0, 1, 1)
        self.lineEdit_sql_input_passwd = QtWidgets.QLineEdit(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_sql_input_passwd.setFont(font)
        self.lineEdit_sql_input_passwd.setObjectName("lineEdit_sql_input_passwd")
        self.gridLayout_5.addWidget(self.lineEdit_sql_input_passwd, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 5, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.sql_logging)
        self.sub_menu = QtWidgets.QWidget()
        self.sub_menu.setObjectName("sub_menu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sub_menu)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_create_new_database = QtWidgets.QPushButton(self.sub_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_create_new_database.setFont(font)
        self.pushButton_create_new_database.setObjectName("pushButton_create_new_database")
        self.gridLayout_3.addWidget(self.pushButton_create_new_database, 3, 1, 1, 1)
        self.pushButton_remove_database = QtWidgets.QPushButton(self.sub_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_remove_database.setFont(font)
        self.pushButton_remove_database.setObjectName("pushButton_remove_database")
        self.gridLayout_3.addWidget(self.pushButton_remove_database, 2, 1, 1, 1)
        self.pushButton_select_db_to_altter = QtWidgets.QPushButton(self.sub_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_select_db_to_altter.setFont(font)
        self.pushButton_select_db_to_altter.setObjectName("pushButton_select_db_to_altter")
        self.gridLayout_3.addWidget(self.pushButton_select_db_to_altter, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 2, 0, 1, 1)
        self.pushButton_close_submenu = QtWidgets.QPushButton(self.sub_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_close_submenu.setFont(font)
        self.pushButton_close_submenu.setObjectName("pushButton_close_submenu")
        self.gridLayout_3.addWidget(self.pushButton_close_submenu, 4, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 5, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.sub_menu)
        self.altter_database_menu = QtWidgets.QWidget()
        self.altter_database_menu.setObjectName("altter_database_menu")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.altter_database_menu)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem11, 9, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 4, 4, 1, 1)
        self.label_select_what_part_of_database_to_altter = QtWidgets.QLabel(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_select_what_part_of_database_to_altter.setFont(font)
        self.label_select_what_part_of_database_to_altter.setObjectName("label_select_what_part_of_database_to_altter")
        self.gridLayout_4.addWidget(self.label_select_what_part_of_database_to_altter, 3, 1, 1, 3)
        self.comboBox_select_database = QtWidgets.QComboBox(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox_select_database.setFont(font)
        self.comboBox_select_database.setObjectName("comboBox_select_database")
        self.gridLayout_4.addWidget(self.comboBox_select_database, 1, 3, 1, 1)
        self.label_select_database_to_altter = QtWidgets.QLabel(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_select_database_to_altter.setFont(font)
        self.label_select_database_to_altter.setObjectName("label_select_database_to_altter")
        self.gridLayout_4.addWidget(self.label_select_database_to_altter, 1, 1, 1, 1)
        self.pushButton_manual_query = QtWidgets.QPushButton(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_manual_query.setFont(font)
        self.pushButton_manual_query.setObjectName("pushButton_manual_query")
        self.gridLayout_4.addWidget(self.pushButton_manual_query, 6, 1, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.altter_database_menu)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 2, 1, 1, 3)
        self.pushButton_edit_tables = QtWidgets.QPushButton(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_edit_tables.setFont(font)
        self.pushButton_edit_tables.setObjectName("pushButton_edit_tables")
        self.gridLayout_4.addWidget(self.pushButton_edit_tables, 4, 1, 1, 1)
        self.pushButton_close_altter_database = QtWidgets.QPushButton(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_close_altter_database.setFont(font)
        self.pushButton_close_altter_database.setObjectName("pushButton_close_altter_database")
        self.gridLayout_4.addWidget(self.pushButton_close_altter_database, 7, 1, 1, 3)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.altter_database_menu)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 8, 1, 1, 3)
        self.pushButton_edit_columns = QtWidgets.QPushButton(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_edit_columns.setFont(font)
        self.pushButton_edit_columns.setObjectName("pushButton_edit_columns")
        self.gridLayout_4.addWidget(self.pushButton_edit_columns, 4, 2, 1, 2)
        self.stackedWidget.addWidget(self.altter_database_menu)
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Settings)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem14, 6, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem15, 0, 1, 1, 1)
        self.comboBox_change_theme = QtWidgets.QComboBox(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox_change_theme.setFont(font)
        self.comboBox_change_theme.setObjectName("comboBox_change_theme")
        self.gridLayout_6.addWidget(self.comboBox_change_theme, 4, 1, 1, 1)
        self.label_change_theme_text = QtWidgets.QLabel(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_change_theme_text.setFont(font)
        self.label_change_theme_text.setObjectName("label_change_theme_text")
        self.gridLayout_6.addWidget(self.label_change_theme_text, 4, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_6.addWidget(self.checkBox_4, 3, 0, 1, 2)
        self.checkBox_confirm_menu_leaving = QtWidgets.QCheckBox(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_confirm_menu_leaving.setFont(font)
        self.checkBox_confirm_menu_leaving.setObjectName("checkBox_confirm_menu_leaving")
        self.gridLayout_6.addWidget(self.checkBox_confirm_menu_leaving, 2, 0, 1, 2)
        self.checkBox_loggin_details = QtWidgets.QCheckBox(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_loggin_details.setFont(font)
        self.checkBox_loggin_details.setObjectName("checkBox_loggin_details")
        self.gridLayout_6.addWidget(self.checkBox_loggin_details, 1, 0, 1, 2)
        self.pushButton_close_settings = QtWidgets.QPushButton(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_close_settings.setFont(font)
        self.pushButton_close_settings.setObjectName("pushButton_close_settings")
        self.gridLayout_6.addWidget(self.pushButton_close_settings, 5, 0, 1, 2)
        self.stackedWidget.addWidget(self.Settings)
        self.remove_database = QtWidgets.QWidget()
        self.remove_database.setObjectName("remove_database")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.remove_database)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem16, 0, 0, 1, 1)
        self.delete_database_pushbutton = QtWidgets.QPushButton(self.remove_database)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.delete_database_pushbutton.setFont(font)
        self.delete_database_pushbutton.setObjectName("delete_database_pushbutton")
        self.gridLayout_7.addWidget(self.delete_database_pushbutton, 4, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem17, 6, 0, 1, 1)
        self.cancel_database_deletion_pushbutton = QtWidgets.QPushButton(self.remove_database)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cancel_database_deletion_pushbutton.setFont(font)
        self.cancel_database_deletion_pushbutton.setObjectName("cancel_database_deletion_pushbutton")
        self.gridLayout_7.addWidget(self.cancel_database_deletion_pushbutton, 4, 1, 1, 1)
        self.comboBox_delete_database = QtWidgets.QComboBox(self.remove_database)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox_delete_database.setFont(font)
        self.comboBox_delete_database.setObjectName("comboBox_delete_database")
        self.comboBox_delete_database.addItem("")
        self.comboBox_delete_database.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_delete_database, 2, 0, 1, 2)
        self.remove_database_label = QtWidgets.QLabel(self.remove_database)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.remove_database_label.setFont(font)
        self.remove_database_label.setObjectName("remove_database_label")
        self.gridLayout_7.addWidget(self.remove_database_label, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.remove_database)
        self.add_database = QtWidgets.QWidget()
        self.add_database.setObjectName("add_database")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.add_database)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.create_database_push_button = QtWidgets.QPushButton(self.add_database)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.create_database_push_button.setFont(font)
        self.create_database_push_button.setObjectName("create_database_push_button")
        self.gridLayout_8.addWidget(self.create_database_push_button, 4, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem18, 5, 0, 1, 1)
        self.text_bow_newdb_name = QtWidgets.QLineEdit(self.add_database)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text_bow_newdb_name.setFont(font)
        self.text_bow_newdb_name.setText("")
        self.text_bow_newdb_name.setObjectName("text_bow_newdb_name")
        self.gridLayout_8.addWidget(self.text_bow_newdb_name, 2, 0, 1, 2)
        self.cancel_newdb_pushbutton = QtWidgets.QPushButton(self.add_database)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cancel_newdb_pushbutton.setFont(font)
        self.cancel_newdb_pushbutton.setObjectName("cancel_newdb_pushbutton")
        self.gridLayout_8.addWidget(self.cancel_newdb_pushbutton, 4, 1, 1, 1)
        self.new_database_label = QtWidgets.QLabel(self.add_database)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_database_label.sizePolicy().hasHeightForWidth())
        self.new_database_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.new_database_label.setFont(font)
        self.new_database_label.setObjectName("new_database_label")
        self.gridLayout_8.addWidget(self.new_database_label, 1, 0, 1, 2)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem19, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.add_database)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem20, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem21, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionHome = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Users/Tuno/Downloads/home.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon)
        self.actionHome.setObjectName("actionHome")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Users/Tuno/Downloads/plus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon1)
        self.actionConnect.setObjectName("actionConnect")
        self.actionclose = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Users/Tuno/Downloads/close.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionclose.setIcon(icon2)
        self.actionclose.setObjectName("actionclose")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MySQL_Python-Tool-1.5"))
        self.settings_button.setText(_translate("MainWindow", "Settings"))
        self.connect_button.setText(_translate("MainWindow", " Connect to MySQL Server "))
        self.close_button.setText(_translate("MainWindow", "Close"))
        self.pushButton_sql_login_login.setText(_translate("MainWindow", "Logging"))
        self.label_sql_login_passwd.setText(_translate("MainWindow", " Password: "))
        self.pushButton_sql_login_close.setText(_translate("MainWindow", "Close"))
        self.label_sql_login_username.setText(_translate("MainWindow", " Username: "))
        self.label_sql_login_ip.setText(_translate("MainWindow", " IP Adress: "))
        self.pushButton_create_new_database.setText(_translate("MainWindow", " Create new database "))
        self.pushButton_remove_database.setText(_translate("MainWindow", " Remove database "))
        self.pushButton_select_db_to_altter.setText(_translate("MainWindow", " Select database to altter "))
        self.pushButton_close_submenu.setText(_translate("MainWindow", " Close "))
        self.label_select_what_part_of_database_to_altter.setText(_translate("MainWindow", " Selet what part of database to altter: "))
        self.label_select_database_to_altter.setText(_translate("MainWindow", " Select Database to altter: "))
        self.pushButton_manual_query.setText(_translate("MainWindow", " Manual Query "))
        self.pushButton_edit_tables.setText(_translate("MainWindow", " Tables "))
        self.pushButton_close_altter_database.setText(_translate("MainWindow", " Close "))
        self.pushButton_edit_columns.setText(_translate("MainWindow", " Columns "))
        self.label_change_theme_text.setText(_translate("MainWindow", " Change theme:"))
        self.checkBox_4.setText(_translate("MainWindow", " Advanced mode:"))
        self.checkBox_confirm_menu_leaving.setText(_translate("MainWindow", " Confirm before closing current menu:"))
        self.checkBox_loggin_details.setText(_translate("MainWindow", " Remember last logging details:"))
        self.pushButton_close_settings.setText(_translate("MainWindow", "Close"))
        self.delete_database_pushbutton.setText(_translate("MainWindow", "Delete"))
        self.cancel_database_deletion_pushbutton.setText(_translate("MainWindow", "Cancel"))
        self.comboBox_delete_database.setItemText(0, _translate("MainWindow", "Test-item1"))
        self.comboBox_delete_database.setItemText(1, _translate("MainWindow", "New Item"))
        self.remove_database_label.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/>Select database to delete:</p></body></html>"))
        self.remove_database_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Select database to delete:</p></body></html>"))
        self.create_database_push_button.setText(_translate("MainWindow", "Create database"))
        self.text_bow_newdb_name.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">databasename</p></body></html>"))
        self.text_bow_newdb_name.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">databasename</p></body></html>"))
        self.cancel_newdb_pushbutton.setText(_translate("MainWindow", "Cancel"))
        self.new_database_label.setText(_translate("MainWindow", " Name for new database:"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionclose.setText(_translate("MainWindow", "close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
