from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        MainWindow.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainmenu = QtWidgets.QWidget()
        self.mainmenu.setEnabled(True)
        self.mainmenu.setObjectName("mainmenu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainmenu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settings_button = QtWidgets.QPushButton(self.mainmenu)
        self.settings_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.settings_button.setFont(font)
        self.settings_button.setObjectName("settings_button")
        self.gridLayout_2.addWidget(self.settings_button, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.connect_button = QtWidgets.QPushButton(self.mainmenu, clicked= lambda: self.connnet_to_mysql_server())
        self.connect_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.connect_button.setFont(font)
        self.connect_button.setObjectName("connect_button")
        self.gridLayout_2.addWidget(self.connect_button, 1, 1, 1, 1)
        self.close_button = QtWidgets.QPushButton(self.mainmenu, clicked= lambda: self.close_app())
        self.close_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.close_button.setFont(font)
        self.close_button.setObjectName("close_button")
        self.gridLayout_2.addWidget(self.close_button, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 2, 1, 1)
        self.connect_button.raise_()
        self.close_button.raise_()
        self.settings_button.raise_()
        self.stackedWidget.addWidget(self.mainmenu)
        self.sql_logging = QtWidgets.QWidget()
        self.sql_logging.setObjectName("sql_logging")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.sql_logging)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.useername_label = QtWidgets.QLabel(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.useername_label.setFont(font)
        self.useername_label.setObjectName("useername_label")
        self.gridLayout_5.addWidget(self.useername_label, 1, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.gridLayout_5.addWidget(self.password_label, 2, 0, 1, 1)
        self.close_logging_pushButton = QtWidgets.QPushButton(self.sql_logging, clicked= lambda: self.return_to_sql_connect_win())
        font = QtGui.QFont()
        font.setPointSize(20)
        self.close_logging_pushButton.setFont(font)
        self.close_logging_pushButton.setObjectName("close_logging_pushButton")
        self.gridLayout_5.addWidget(self.close_logging_pushButton, 3, 2, 1, 1)
        self.log_in_logging_pushButton = QtWidgets.QPushButton(self.sql_logging, clicked= lambda: self.open_altter_database_menu())
        font = QtGui.QFont()
        font.setPointSize(20)
        self.log_in_logging_pushButton.setFont(font)
        self.log_in_logging_pushButton.setObjectName("log_in_logging_pushButton")
        self.gridLayout_5.addWidget(self.log_in_logging_pushButton, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.sql_logging)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.sql_logging)
        self.sub_menu = QtWidgets.QWidget()
        self.sub_menu.setObjectName("sub_menu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sub_menu)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.sub_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 3, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.sub_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.sub_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 2, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.sub_menu, clicked= lambda: self.return_to_sql_login_menu())
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 4, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 5, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.sub_menu)
        self.altter_database_menu = QtWidgets.QWidget()
        self.altter_database_menu.setObjectName("altter_database_menu")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.altter_database_menu)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 0, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 9, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 4, 4, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 1, 1, 3)
        self.comboBox = QtWidgets.QComboBox(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_4.addWidget(self.pushButton_8, 6, 1, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.altter_database_menu)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 2, 1, 1, 3)
        self.pushButton_6 = QtWidgets.QPushButton(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 4, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.altter_database_menu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_4.addWidget(self.pushButton_7, 7, 1, 1, 3)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.altter_database_menu)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 8, 1, 1, 3)
        self.stackedWidget.addWidget(self.altter_database_menu)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionHome = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Users/Tuno/Downloads/home.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon)
        self.actionHome.setObjectName("actionHome")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Users/Tuno/Downloads/plus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon1)
        self.actionConnect.setObjectName("actionConnect")
        self.actionclose = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Users/Tuno/Downloads/close.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionclose.setIcon(icon2)
        self.actionclose.setObjectName("actionclose")
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addAction(self.actionclose)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MySQL_Python-Tool-1.5"))
        self.settings_button.setText(_translate("MainWindow", "Settings"))
        self.connect_button.setText(_translate("MainWindow", "Connect to MySQL Server"))
        self.close_button.setText(_translate("MainWindow", "Close"))
        self.useername_label.setText(_translate("MainWindow", " Username: "))
        self.password_label.setText(_translate("MainWindow", " Password: "))
        self.close_logging_pushButton.setText(_translate("MainWindow", "Close"))
        self.log_in_logging_pushButton.setText(_translate("MainWindow", "Logging"))
        self.label_3.setText(_translate("MainWindow", " IP Adress: "))
        self.pushButton_3.setText(_translate("MainWindow", " Create new database "))
        self.pushButton_2.setText(_translate("MainWindow", " Remove database "))
        self.pushButton.setText(_translate("MainWindow", " Select database to altter "))
        self.pushButton_4.setText(_translate("MainWindow", " Close "))
        self.pushButton_5.setText(_translate("MainWindow", " Columns "))
        self.label_2.setText(_translate("MainWindow", " Selet what part of database to altter: "))
        self.label.setText(_translate("MainWindow", " Select Database to altter: "))
        self.pushButton_8.setText(_translate("MainWindow", " Manual Query "))
        self.pushButton_6.setText(_translate("MainWindow", " Tables "))
        self.pushButton_7.setText(_translate("MainWindow", " Close "))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionclose.setText(_translate("MainWindow", "close"))

    def connnet_to_mysql_server(self):
        self.stackedWidget.setCurrentIndex(1)

    def return_to_sql_login_menu(self):
        self.stackedWidget.setCurrentIndex(1)

    def return_to_sql_connect_win(self):
        self.stackedWidget.setCurrentIndex(0)

    def open_altter_database_menu(self):
        self.stackedWidget.setCurrentIndex(2)

    def close_app(self):
        sys.exit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
